language: generic

sudo: false


matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.4 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=3.4 }
    - { os: osx, env: PYTHON_VERSION=3.5 }

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
    - source devtools/travis-ci/install.sh
    - conda install -yq scipy pytest numba
    - pip install hypothesis
    - pip install -e .

script:
    - py.test -vs
